# EasyCTF Configuration File

# Language Settings
language: "ja"  # Available: "en" (English), "ja" (Japanese)

# Default Game Settings (used when creating new games)
default-game:
  # Enable automatic game start when minimum players join
  auto-start-enabled: false
  
  # Minimum players required to auto-start a game (if enabled)
  min-players: 2
  
  # Maximum players per team
  max-players-per-team: 10
  
  # Respawn delay in seconds (base + kill penalty)
  respawn-delay-base: 10
  respawn-delay-per-death: 2  # Additional seconds per death
  respawn-delay-max: 20  # Maximum respawn delay
  
  # Force PVP during combat phase (ignore server pvp settings)
  force-pvp: true

# Default Phase Settings
default-phases:
  # Phase 1: Build phase duration in seconds (default: 2 minutes)
  build-duration: 120
  
  # Build phase game mode for players
  # Options: ADVENTURE, SURVIVAL, CREATIVE
  # ADVENTURE: Limited interaction, prevents most building
  # SURVIVAL: Normal building/breaking with tools (default)
  # CREATIVE: Unlimited building, flying, instant break
  build-phase-gamemode: "SURVIVAL"
  
  # Phase 2: Combat phase duration in seconds (default: 2 minutes)
  combat-duration: 120
  
  # Countdown after combat phase ends before next round starts (in seconds)
  combat-end-countdown: 15
  
  # Phase 3: Result phase duration in seconds (default: 15 seconds)
  result-duration: 15
  
  # Intermediate result duration for matches (seconds)
  intermediate-result-duration: 15

# Game Mechanics
mechanics:
  # Spawn protection duration in seconds
  spawn-protection-duration: 3
  
  # Enemy spawn area protection radius in blocks
  # Prevents placing non-team blocks near enemy spawn
  enemy-spawn-protection-radius: 5
  
  # NOT IMPLEMENTED YET:
  # flag-drop-timeout: 30  # Flag auto-return timeout in seconds
  # allow-ender-pearls: false
  # allow-elytra: false
  # allow-vehicles: false

# Match Settings
match:
  # Default number of games to play in a match
  default-target: 3
  
  # Interval between games in seconds
  interval-duration: 15

# Currency Settings
currency:
  # Currency display name
  name: "G"
  
  # Initial currency per team at game start
  initial: 50
  
  # Phase end bonus (given at end of combat phase)
  phase-end-bonus: 50
  
  # Kill rewards
  kill-reward: 10
  kill-assist-reward: 5
  carrier-kill-reward: 20
  carrier-kill-assist-reward: 10
  
  # Kill streak bonuses (additional currency per consecutive kill)
  kill-streak-bonus:
    2-kills: 5    # +5G for 2 consecutive kills
    3-kills: 10   # +10G for 3 consecutive kills
    4-kills: 15   # +15G for 4 consecutive kills
    5-plus-kills: 20  # +20G for 5+ consecutive kills
  
  # Capture rewards
  capture-reward: 30
  capture-assist-reward: 15

# Shop Settings
shop:
  # Enable shop system
  enabled: true
  
  # Shop usage range from spawn point (blocks)
  use-range: 15
  
  # Discount rates based on score difference
  discount:
    1-point: 0.1    # 10% off
    2-point: 0.2    # 20% off
    3-point: 0.3    # 30% off
    4-point-plus: 0.4  # 40% off

# Shield Settings
shield:
  enabled: true                     # Enable/disable shield system
  max-shield: 100                   # Maximum shield value
  decrease-rate: 2.0                # Decrease rate on enemy blocks (per 0.5 seconds)
  recovery-rate: 5.0                # Recovery rate on friendly blocks (per 0.5 seconds)
  warning-threshold: 40             # Shield value for warning message
  critical-threshold: 20            # Shield value for critical warning
  damage-interval: 1000             # Damage interval when shield is 0 (milliseconds)
  damage-amount: 1.5                # Damage amount when shield is 0

# Debug Settings
debug:
  # Enable debug messages
  enabled: false
  
  # Log level (INFO, WARNING, SEVERE)
  log-level: "INFO"