name: Release to Modrinth

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew clean shadowJar
      
    - name: List build output
      run: |
        echo "Contents of build/libs:"
        ls -la build/libs/ || echo "build/libs directory not found"
      
    - name: Extract version from tag
      id: version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      
    - name: Find JAR file
      id: jar
      run: |
        # shadowJarで生成されるJARファイルを探す（EasyCTF-*.jar）
        JAR_FILE=$(find build/libs -name "EasyCTF-*.jar" -type f | head -1)
        if [ -z "$JAR_FILE" ]; then
          echo "Error: No EasyCTF JAR file found in build/libs/"
          ls -la build/libs/
          exit 1
        fi
        echo "JAR_PATH=$JAR_FILE" >> $GITHUB_OUTPUT
        echo "JAR_NAME=$(basename $JAR_FILE)" >> $GITHUB_OUTPUT
        echo "Found JAR: $JAR_FILE"
        
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: ${{ steps.jar.outputs.JAR_PATH }}
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Upload to Modrinth
      uses: Kir-Antipov/mc-publish@v3.3
      with:
        modrinth-id: ${{ secrets.MODRINTH_PROJECT_ID }}
        modrinth-token: ${{ secrets.MODRINTH_PAT }}
        
        files: ${{ steps.jar.outputs.JAR_PATH }}
        name: "EasyCTF v${{ steps.version.outputs.VERSION }}"
        version: ${{ steps.version.outputs.VERSION }}
        version-type: release
        
        loaders: |
          paper
          
        game-versions: |
          1.21.5
          
        dependencies: |
          paper-api(required)
          
        changelog: |
          See [CHANGELOG.md](https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md) for details.
          
          Auto-generated release notes:
          ${{ github.event.release.body }}
        
        retry-attempts: 2
        retry-delay: 10000